In [1]:
import numpy as np
import pandas as pd
import datetime

In [2]:
dataset = pd.read_csv("grossing2017-2011.csv")

In [3]:
dataset.head()

,colocação,título_brasileiro,título_original,distribuidora,renda,publico,salas_abertura,estreia
0,1,Velozes e furiosos 8,The Fate of the Furious,Universal,133420000,8504737,1512,2017-04-13
1,2,Liga da Justiça,Justice league,Warner,131218000,8416544,1582,2017-11-16
2,3,A Bela e a Fera,Beauty and the Beast,Disney,130098000,8309801,1399,2017-03-16
3,4,Meu malvado favorito 3,Despicable me 3,Universal,126007000,8996130,1319,2017-06-29
4,5,Mulher-Maravilha,Wonder Woman,Warner,109700000,7053736,1287,2017-01-06

## Pytrends

In [4]:
from pytrends.request import TrendReq

In [5]:
pytrends = TrendReq(hl='en-US', tz=360) #CONECTANDO COM O GOOGLE

In [10]:
movies = dataset.iloc[:,1]
movies

0                                 Velozes e furiosos 8
1                                      Liga da Justiça
2                                      A Bela e a Fera
3                               Meu malvado favorito 3
4                                     Mulher-Maravilha
5                        Homem-Aranha: De volta ao lar
6                                       Thor: Ragnarok
7                                                Logan
8                               Minha mãe é uma peça 2
9                                             A cabana
10                         Moana - Um mar de aventuras
11                              Guardiões da Galáxia 2
12                         Cinquenta tons mais escuros
13                                        It - A coisa
14           Piratas do Caribe - A vingança de Salazar
15                         Star Wars - Os últimos jedi
16                                      Extraordinário
17                                             A múmia
18                                 O poderoso chefinho
19                      Planeta dos macacos - A guerra
20                    Transformers: O último cavaleiro
21                      Annabelle 2 - A criação do mal
22                                            Carros 3
23                                    Assassin's Creed
24                            Kong - A ilha da caveira
25                                    A grande muralha
26                                     Emoji - O filme
27                      La la Land - Cantando estações
28                                         Passageiros
29                Polícia Federal - A lei é para todos
                            ...
863                                  CAPITÃES DA AREIA
864     HARRY POTTER E AS RELÍQUIAS DA MORTE - PARTE 1
865                              AS AVENTURAS DE SAMMY
866                               QUAL É O SEU NÚMERO?
867                       MISSÃO MADRINHA DE CASAMENTO
868                                             UM DIA
869                NÃO SE PREOCUPE, NADA VAI DAR CERTO
870                                         CÓPIA FIEL
871          O DIÁRIO DE UM BANANA 2: RODDICK É O CARA
872                             POTICHE: ESPOSA TROFÉI
873                             MUITA CALMA NESSA HORA
874                                    TUPO PELO PODER
875                              NAMORADOS PARA SEMPRE
876                                      JOGO DO PODER
877                                           BIUTIFUL
878                                 FAMÍLIA VENDE TUDO
879                           NÃO TENHA MEDO DO ESCURO
880                                  BRASIL ANIMADO 3D
881                                    O PODER E A LEI
882                              O GAROTO DE BICICLETA
883                                     O URSINHO POOH
884                                   PRONTA PARA AMAR
885    MEDIANERAS: BUENOS AIRES DA ERA DO AMOR VIRTUAL
886                      MINHAS TARDES COM MARGUERITTE
887                             ASSASSINO A PREÇO FIXO
888                                        A INQUILINA
889                              ASSALTO EM DOSE DUPLA
890                                          BURLESQUE
891                                  UM LUGAR QUALQUER
892                                    HOMENS E DEUSES
Name: título_brasileiro, Length: 893, dtype: object

In [13]:
def sixMonthsEarlier(releaseDay):
    data = datetime.date.fromisoformat(releaseDay)
    sixMonthsAgo = datetime.timedelta(days=180)
    return str(data - sixMonthsAgo)

def getTimeFrame(i):
    to_tf = dataset.loc[i,'estreia']
    from_tf =  sixMonthsEarlier(to_tf)
    tf = str(from_tf +' '+ to_tf)
    tf = str(from_tf + " " + to_tf)
    return tf

In [8]:
#kw_list = movies
#pytrends.build_payload(kw_list, timeframe = tf , geo='BR')

In [158]:
kw_list = movies.head()
kw_list

0      Velozes e furiosos 8
1           Liga da Justiça
2           A Bela e a Fera
3    Meu malvado favorito 3
4          Mulher-Maravilha
Name: título_brasileiro, dtype: object

In [164]:
for i in range(5):
    print(kw_list[i] + " " +getTimeFrame(i))

Velozes e furiosos 8 2016-10-15 2017-04-13
Liga da Justiça 2017-05-20 2017-11-16
A Bela e a Fera 2016-09-17 2017-03-16
Meu malvado favorito 3 2016-12-31 2017-06-29
Mulher-Maravilha 2016-07-10 2017-01-06

In [166]:
for i in range(5):
    pytrends.build_payload(kw_list[i], timeframe = getTimeFrame(i), geo='BR')
    interest = pytrends.interest_over_time()
    interest.reset_index().drop('date', axis=1)

ResponseError: The request failed: Google returned a response with code 400.

In [160]:
movies_insterest_over_time.reset_index().drop('date', axis=1)

,Velozes e furiosos 8,Liga da Justiça,A Bela e a Fera,Meu malvado favorito 3,Mulher-Maravilha,isPartial
date,,,,,,
2016-07-10,3,10,7,1,0,False
2016-07-11,2,6,5,0,0,False
2016-07-12,3,7,4,0,0,False
2016-07-13,3,7,5,0,0,False
2016-07-14,3,7,5,0,0,False
2016-07-15,2,8,5,0,0,False
2016-07-16,4,9,6,0,0,False
2016-07-17,5,11,7,0,0,False
2016-07-18,3,10,6,0,0,False
2016-07-19,2,7,5,0,0,False
2016-07-20,2,9,5,0,0,False
2016-07-21,2,6,4,0,0,False
2016-07-22,2,8,5,0,0,False
2016-07-23,3,32,6,0,0,False
2016-07-24,3,45,6,0,0,False
2016-07-25,4,29,5,0,0,False
2016-07-26,2,20,5,0,0,False
2016-07-27,3,16,6,0,0,False
2016-07-28,2,15,5,0,0,False
2016-07-29,3,14,4,0,0,False
2016-07-30,2,16,9,0,0,False
2016-07-31,2,15,7,1,0,False
2016-08-01,2,10,6,0,0,False
2016-08-02,2,10,6,0,0,False
2016-08-03,2,9,5,0,0,False
2016-08-04,1,7,3,0,0,False
2016-08-05,2,8,4,0,0,False
2016-08-06,1,9,6,0,0,False
2016-08-07,2,9,6,0,0,False
2016-08-08,2,8,5,0,1,False
...,...,...,...,...,...,...
2016-12-08,3,9,8,0,0,False
2016-12-09,4,10,8,0,0,False
2016-12-10,11,10,6,0,0,False
2016-12-11,12,12,8,2,0,False
2016-12-12,57,8,5,0,0,False
2016-12-13,27,8,6,1,0,False
2016-12-14,16,8,5,6,0,False
2016-12-15,11,9,7,12,0,False
2016-12-16,9,10,5,7,0,False
2016-12-17,11,13,6,5,0,False
2016-12-18,9,10,8,4,0,False
2016-12-19,4,11,5,4,0,False
2016-12-20,4,11,9,4,0,False
2016-12-21,5,10,6,2,0,False
2016-12-22,5,13,6,1,0,False
2016-12-23,4,9,7,3,0,False
2016-12-24,5,13,13,2,0,False
2016-12-25,7,13,20,2,0,False
2016-12-26,4,10,24,2,0,False
2016-12-27,3,10,100,1,0,False
2016-12-28,4,11,19,1,0,False
2016-12-29,5,10,11,1,0,False
2016-12-30,5,10,14,2,0,False
2016-12-31,5,11,11,2,0,False
2017-01-01,8,15,12,2,0,False
2017-01-02,5,10,10,0,0,False
2017-01-03,6,11,10,2,0,False
2017-01-04,5,10,6,1,0,False
2017-01-05,4,8,7,1,1,False
2017-01-06,3,9,9,1,0,False

In [156]:
pytrends.interest_over_time()

            Veloses e furiosos 8  isPartial
date
2016-10-15                    12      False
2016-10-16                    12      False
2016-10-17                    18      False
2016-10-18                     0      False
2016-10-19                     9      False
2016-10-20                     0      False
2016-10-21                    10      False
2016-10-22                    13      False
2016-10-23                    13      False
2016-10-24                     9      False
2016-10-25                     9      False
2016-10-26                     9      False
2016-10-27                     9      False
2016-10-28                     0      False
2016-10-29                     0      False
2016-10-30                     0      False
2016-10-31                     9      False
2016-11-01                    10      False
2016-11-02                     0      False
2016-11-03                     9      False
2016-11-04                     0      False
2016-11-05                     0      False
2016-11-06                    12      False
2016-11-07                     0      False
2016-11-08                     0      False
2016-11-09                     0      False
2016-11-10                    10      False
2016-11-11                     0      False
2016-11-12                    13      False
2016-11-13                    13      False
...                          ...        ...
2017-03-15                    12      False
2017-03-16                    20      False
2017-03-17                    22      False
2017-03-18                    37      False
2017-03-19                    17      False
2017-03-20                    11      False
2017-03-21                    14      False
2017-03-22                     8      False
2017-03-23                     8      False
2017-03-24                    18      False
2017-03-25                    15      False
2017-03-26                    19      False
2017-03-27                     8      False
2017-03-28                    12      False
2017-03-29                    14      False
2017-03-30                    14      False
2017-03-31                    28      False
2017-04-01                    22      False
2017-04-02                    30      False
2017-04-03                    28      False
2017-04-04                    16      False
2017-04-05                    33      False
2017-04-06                    26      False
2017-04-07                    48      False
2017-04-08                    25      False
2017-04-09                    48      False
2017-04-10                    42      False
2017-04-11                    42      False
2017-04-12                    55      False
2017-04-13                   100      False

[181 rows x 2 columns]

In [9]:
movies_insterest_over_time = pytrends.interest_over_time()

In [20]:
movies_insterest_over_time.reset_index().drop('date', axis=1).transpose()

,0,1,2,3,4,5,6,7,8,9,...,171,172,173,174,175,176,177,178,179,180
Velozes e furiosos 8,2,1,1,1,1,0,1,1,1,2,...,8,10,13,13,16,21,19,21,29,50
Liga da Justiça,6,6,3,3,3,3,3,4,4,4,...,4,4,4,5,5,6,4,3,4,3
A Bela e a Fera,3,4,2,2,2,2,2,2,3,2,...,21,19,19,19,27,31,16,15,16,20
Meu malvado favorito 3,1,0,0,0,0,0,0,0,0,0,...,0,1,0,0,1,1,0,0,0,1
Mulher-Maravilha,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
isPartial,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False